name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Start ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        export CHROME_BIN=/usr/bin/chromium-browser

    - name: Run Tests
      run: npm test
