name: Puppeteer Tests (with Cache)

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js with cache
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies with npm ci
        run: npm ci

      - name: Run Puppeteer Tests
        run: npm test
